spring.application.name=microjobsPlatform
spring.data.mongodb.uri=mongodb+srv://RaulAdmin:***REMOVED***@microjobs.fwkk5km.mongodb.net/microjobsdb?retryWrites=true&w=majority&appName=microjobs
server.port=8080