spring.application.name=microjobsPlatform
spring.data.mongodb.uri=mongodb+srv://RaulAdmin:***REMOVED***@microjobs.fwkk5km.mongodb.net/microjobsPlatform?retryWrites=true&w=majority&appName=microjobs

server.port=8080
security.jwt.secret-key=TXlTdXBlclNlY3JldEtleUZvckpXVEF1dGhFbmNyeXB0aW9uMTIzNDU2Nzg5MDEyMzQ1Ng==
security.jwt.expiration-time=86400000
